[package]
name = "xvm"
version = "0.1.0"
authors = ["Evgeny Yakovlev <insoreiges@gmail.com>"]

[dependencies]
num = "0.1.0"
rlibc = "1.0.0"
Hypervisor_framework = { git = "https://github.com/warfish/hypervisor-framework-rs.git" }